### ISSUE TITLE
Open from taskbar does not locate accounts.json

### ISSUE THREAD

**Issue by pbelsley97** [ynk/LolAccountManager#13]
When opening the program using a taskbar search (windows key -> lolaccountmanager.exe -> enter), the program is unable to locate the accounts.json file stored in the same directory as the exe.

Looking at Procmon, It instead attempts to open C:\Windows:\SysWOW64\accounts.json when tested in windows 11. 

For it to work as expected, I have to hit show file location then open it from the resulting explorer window.

**Comment by ynk** [comment]
I am unable to recreate this issue, can you tell me a bit more?

**Comment by pbelsley97** [comment]
Here's a link to a screen recording of it in action, and the procmon CSV for 2 attempts to open the file:


https://cdn.discordapp.com/attachments/147086047057149952/1171458325074944081/Lol-Account--Manager-Bug1.mp4

[LolAccountManager.CSV](https://github.com/ynk/LolAccountManager/files/13281808/LolAccountManager.CSV)

**Comment by ynk** [comment]
Thank you, will look into this!

**Comment by ynk** [comment]
I have changed the way accounts.json is loaded since I can't recreate this problem in a Win11 VM. 
See [#e23188e ](https://github.com/ynk/LolAccountManager/commit/e23188ec2a1210fdb585a06aceefcebbb73cdb9d)

Could you build the repo and try it out? Or would you like me to send you a release version. 

Once the program is launched it will write the executed location in the debug window.

**Comment by pbelsley97** [comment]
Built the update, when I try that version it now gives me a popup saying "Could not find file 'C:\Windows\sysem32\accounts.json'."

debug menu correctly notes that it's being run from ~\Downloads\LolAccountManager\
